- name: installing packages in loops
  hosts: frontend
  become: yes
  tasks:
  - name: print packages
    ansible.builtin.package:
     name: "{{ item }}"
     state: present
    loop:
    - mysql
    - nginx
    - html