- name: hello world
  hosts: local
  connection: local  # when we use local no need to use ansible username and password
  tasks:
  - name: print hello world script
    ansible.builtin.debug:
    msg: "hello world"
    
    

