- name: functions
  hosts: local
  connection: local
  vars:
   persons: "rakesh,rajiv,lankesh"
  tasks:
  - name: check undefined variables
    ansible.builtin.debug:
     msg: "hey {{ person | default('ramesh') }}" #this takes default as ramesh if we dont define person

  - name: print names
    ansible.builtin.debug:
     msg: "hey {{ persons | split(',') }}" 
     #  answer with only person "msg": "hey rakesh,rajiv,lankesh"
     #  answer with person and spilt "msg": "hey ['rakesh', 'rajiv', 'lankesh']"
    
  - name: convert map to List
    vars:
     details:
      person: shashi
      standard: 10th
    ansible.builtin.debug:
     msg: "hey {{ details | dict2items }}"
     #answer:  "msg": "hey [{'key': 'person', 'value': 'shashi'}, {'key': 'standard', 'value': '10th'}]"

  - name: convert list to map
    vars:
     details:
     - {'key': 'person', 'value': 'shashi'}
     - {'key': 'standard', 'value': '10th'}
    ansible.builtin.debug:
     msg: "hey {{ details | items2dict }}"
  
  - name: convert to uppercase
    vars:
     name: "nice-to-see-you"
    ansible.builtin.debug:
     msg: " hello {{ name | upper}}"

  - name: convert to uppercase
    vars:
     name: "JINDHAL"
    ansible.builtin.debug:
     msg: " hello {{ name | lower}}"

  - name: check IP address is valid or not
    vars:
      ip: "192.168.1.1"
    ansible.builtin.debug:
      msg: "{{ ip | ansible.utils.ipaddr }}"