- name: create ec2 and r53 records
  hosts: localhost
  connection: local
  vars:
    instances:
    - mysql
    - backend
    - frontend
    subnet_id: subnet-09ea96efc16499950
    sg_id: sg-02bf3b4a65ca16980
    zone: rojahanumantharaju.site
  tasks:
  - name: create ec2
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: ami-09c813fb71547fc4f
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  